### ISSUE TITLE
Incorrect Latitude normalization

### ISSUE THREAD

**Issue by Sufaev** [WorldWindEarth/WorldWindJava#62] opened 2019-07-12 17:04 UTC
### Description
Angle has incorrect normalization function. It does not determine whether whether the latitude is in the north or south hemisphere.
For example 182 degrees of latitude should be normalized -2 degree not 2.

**Expected behavior:** 
```
    public static double normalizedDegreesLatitude(double degrees) {
        double lat = degrees % 180;
        double normalizedLat = lat > 90 ? 180 - lat : lat < -90 ? -180 - lat : lat;
        // Determine whether whether the latitude is in the north or south hemisphere
        int numEquatorCrosses = (int) (degrees / 180);
        return (numEquatorCrosses % 2 == 0) ? normalizedLat : -normalizedLat;
    }
```

**Actual behavior:** 
```
    public static double normalizedDegreesLatitude(double degrees) {
        double lat = degrees % 180;
        return lat > 90 ? 180 - lat : lat < -90 ? -180 - lat : lat;
    }
```

### Steps to Reproduce
Try to put 182 degrees into new Location or any other latitude logic.

**Reproduces how often:** 
This bug almost never appears. I found it just by comparing Java and Android sources when I have searched solution to normalize latitude in my application.

### Operating System and Version 
Any

**Comment by wcmatthysen** [comment] 2019-07-12 17:38
@Sufaev, thanks for spotting the bug-fix. We came to the conclusion that the normalization was incorrect in issue #46.

**Comment by Sufaev** [comment] 2019-07-12 18:37
Oh, sorry for duplicate issue.

**Comment by wcmatthysen** [comment] 2019-07-13 17:14
I'm closing this as duplicate of issue #46.

**Closed by wcmatthysen** 2019-07-13 17:14 UTC
